import Foundation

/// G4 catalog: the 1000-item goal starts from a REAL seed (local skills,
/// CLIs, cmux binaries, MCP registries, macrix tools) generated by
/// triqhub/catalog/generate.py. The server reads the installed copy at
/// ~/.config/macrix/catalog.json. Growth loop: generator re-runs add
/// curated batches; schema version gates readers.
public enum Catalog {
    public struct Entry: Codable {
        let id: String
        let kind: String
        let name: String
        let source: String
        let description: String
        let installed: Bool
    }
    public struct Doc: Codable {
        let version: Int
        let generated: String
        let count: Int
        let target: Int
        let entries: [Entry]
    }

    public static func load() -> Doc? {
        let p = (NSHomeDirectory() as NSString).appendingPathComponent(".config/macrix/catalog.json")
        guard let data = try? Data(contentsOf: URL(fileURLWithPath: p)),
              let doc = try? JSONDecoder().decode(Doc.self, from: data),
              doc.version == 1 else { return nil }
        return doc
    }

    public static func stats() -> String {
        guard let doc = load() else { return "catalog unavailable: reinstall ~/.config/macrix/catalog.json." }
        var kinds: [String: Int] = [:]
        for e in doc.entries { kinds[e.kind, default: 0] += 1 }
        let parts = kinds.sorted { $0.value > $1.value }.map { "\($0.key)=\($0.value)" }.joined(separator: " ")
        return "catalog v\(doc.version) (\(doc.generated)): \(doc.entries.count)/\(doc.target) — \(parts)"
    }

    public static func search(_ query: String, limit: Int) -> String {
        guard let doc = load() else { return "catalog unavailable." }
        let q = query.lowercased()
        let hits = doc.entries.filter {
            $0.name.lowercased().contains(q) || $0.description.lowercased().contains(q)
                || $0.kind.lowercased().contains(q)
        }.prefix(max(1, min(limit, 30)))
        if hits.isEmpty { return "no catalog entries match '\(query)'." }
        return hits.map { "- [\($0.kind)] \($0.name) — \(($0.description.isEmpty ? $0.source : $0.description).prefix(120))" }
            .joined(separator: "\n")
    }
}
